# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_agency', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_name', models.CharField(blank=True, max_length=500)),
                ('serial_number', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, choices=[(b'Valid', b'Valid'), (b'Sold', b'Sold')], max_length=500)),
                ('tag_number', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('approval_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.ApprovalAgency')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateField(default=datetime.datetime.now)),
                ('renewal_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('manufacture_name', models.CharField(blank=True, max_length=500)),
                ('model_number', models.CharField(blank=True, max_length=500)),
                ('a_number', models.CharField(blank=True, max_length=500)),
                ('license_decal_number', models.CharField(blank=True, max_length=500)),
                ('document_description', models.CharField(blank=True, max_length=500)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.AssetType')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=500)),
                ('document_type_desc', models.CharField(blank=True, max_length=500)),
                ('asset_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.AssetType')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.DocumentType'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.Document'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.AssetType'),
        ),
    ]
