# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_name', models.CharField(max_length=500)),
                ('approval_agency', models.CharField(max_length=500)),
                ('manufacture_serial_number', models.CharField(max_length=150)),
                ('a_number', models.CharField(max_length=150)),
                ('tag_number', models.CharField(max_length=150)),
            ],
        ),
    ]
