# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to=b'uploads/%Y/%m/%d/'),
        ),
    ]
