# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_name', models.CharField(max_length=500)),
                ('document_type', models.CharField(max_length=250)),
                ('model_number', models.CharField(max_length=150)),
                ('a_number', models.CharField(max_length=150)),
                ('decal_number', models.CharField(max_length=150)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.Asset')),
            ],
        ),
    ]
