# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdocument',
            old_name='asset_id',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='assetdocument',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='asset_type_id',
            new_name='asset_type',
        ),
    ]
