# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='manufacture_serial_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='decal_number',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='license_decal_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='renewal_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='a_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='a_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='document',
            name='asset',
        ),
        migrations.AddField(
            model_name='document',
            name='asset',
            field=models.ManyToManyField(to='Documents.Asset'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='model_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
