# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20170319_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='asset',
            field=models.ManyToManyField(to='Documents.Asset'),
        ),
    ]
