# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20170315_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='renewal_date',
            field=models.DateField(blank=True),
        ),
    ]
