# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20170426_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCR_Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_Date_left', models.CharField(max_length=500)),
                ('document_Date_top', models.CharField(max_length=500)),
                ('document_Date_right', models.CharField(max_length=500)),
                ('document_Date_bottom', models.CharField(max_length=500)),
                ('document_Date_letterset', models.CharField(blank=True, max_length=500)),
                ('document_Date_Regex', models.CharField(blank=True, max_length=500)),
                ('document_Date_MarkingType', models.CharField(blank=True, max_length=500)),
                ('locument_Date_texttype', models.CharField(blank=True, max_length=500)),
                ('license_decal_left', models.CharField(max_length=500)),
                ('license_decal_top', models.CharField(max_length=500)),
                ('license_decal_right', models.CharField(max_length=500)),
                ('license_decal_bottom', models.CharField(max_length=500)),
                ('license_decal_letterset', models.CharField(blank=True, max_length=500)),
                ('license_decal_Regex', models.CharField(blank=True, max_length=500)),
                ('license_decal_Markingtype', models.CharField(blank=True, max_length=500)),
                ('license_decal_texttype', models.CharField(blank=True, max_length=500)),
                ('renewal_date_left', models.CharField(max_length=500)),
                ('renewal_date_top', models.CharField(max_length=500)),
                ('renewal_date_right', models.CharField(max_length=500)),
                ('renewal_date_bottom', models.CharField(max_length=500)),
                ('renewal_date_letterset', models.CharField(blank=True, max_length=500)),
                ('renewal_date_regex', models.CharField(blank=True, max_length=500)),
                ('renewal_date_texttype', models.CharField(blank=True, max_length=500)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.DocumentType')),
            ],
        ),
    ]
