# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_approvalagency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApprovalAgency',
            new_name='AssetType',
        ),
        migrations.RenameField(
            model_name='assettype',
            old_name='approval_agency',
            new_name='asset_type',
        ),
    ]
