# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20170310_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_agency', models.CharField(max_length=500)),
            ],
        ),
    ]
