# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20170315_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
