# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_ocr_coordinates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OCR_Coordinates',
            new_name='OCRCoordinates',
        ),
    ]
