# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_approvalagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='approval_agency',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=500),
        ),
    ]
