# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_auto_20170523_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
