# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='test',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
